name: pomodoro_land
description: The Pomodoro Focus application is integrated with clockify and taiga to speed up integration and maintain focus on tasking.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  google_fonts: ^3.0.1
  hive: ^2.2.3
  path_provider: ^2.0.11
  intl: ^0.18.0
  flutter_bloc: ^8.1.1
  audioplayers: ^2.0.0
  http: ^0.13.5
  collection: ^1.16.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
